# Generated by Django 4.1.6 on 2023-02-07 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, help_text='original page image', null=True, upload_to='pages', verbose_name='Page Image')),
                ('category', models.CharField(default='', max_length=40)),
                ('status', models.CharField(choices=[('new', 'New'), ('segmented', 'Segmented'), ('assigned', 'Assigned'), ('corrected', 'Corrected'), ('skipped', 'Skipped')], default='new', max_length=10)),
                ('language', models.CharField(choices=[('', 'Select Language'), ('assamese', 'Assamese'), ('bengali', 'Bengali'), ('english', 'English'), ('gujarati', 'Gujarati'), ('hindi', 'Hindi'), ('kannada', 'Kannada'), ('malayalam', 'Malayalam'), ('manipuri', 'Manipuri'), ('marathi', 'Marathi'), ('oriya', 'Oriya'), ('punjabi', 'Punjabi'), ('tamil', 'Tamil'), ('telugu', 'Telugu'), ('urdu', 'Urdu')], default='', max_length=20)),
                ('assigned_timestamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('corrected_timestamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(blank=True, default=None, help_text='Indicates the user that corrects this pages segmentation', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_related_name': 'pages',
            },
        ),
    ]
