# Generated by Django 4.1.6 on 2023-02-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='parent',
            field=models.CharField(default='', help_text='This field stores the ID or information of the source of the page', max_length=50),
        ),
    ]
