# Generated by Django 4.1.6 on 2023-03-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_alter_page_image_alter_page_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('segmented', 'Segmented'), ('assigned', 'Assigned'), ('corrected', 'Corrected'), ('skipped', 'Skipped'), ('sent', 'Sent')], default='new', max_length=10),
        ),
    ]
