# Generated by Django 4.1.6 on 2023-03-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_alter_page_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='language',
            field=models.CharField(choices=[('', 'Select Language'), ('assamese', 'Assamese'), ('bengali', 'Bengali'), ('english', 'English'), ('gujarati', 'Gujarati'), ('hindi', 'Hindi'), ('kannada', 'Kannada'), ('malayalam', 'Malayalam'), ('manipuri', 'Manipuri'), ('marathi', 'Marathi'), ('oriya', 'Oriya'), ('punjabi', 'Punjabi'), ('tamil', 'Tamil'), ('telugu', 'Telugu'), ('urdu', 'Urdu'), ('bodo', 'Bodo'), ('dogri', 'Dogri'), ('konkani', 'Konkani'), ('kashmiri', 'Kashmiri'), ('maithili', 'Maithili'), ('nepali', 'Nepali'), ('sindhi', 'Sindhi'), ('santali', 'Santali'), ('sanskrit', 'Sanskrit')], default='', max_length=20),
        ),
    ]
