# Generated by Django 4.1.6 on 2023-04-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_alter_page_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='polygon',
            field=models.BooleanField(default=False, help_text='This indicates that when the page is showed for segmentation to the user, polygon will decide whether to show the label studio in the form of rectangle or polygons'),
        ),
    ]
