# Generated by Django 4.1.6 on 2023-07-08 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_page_polygon'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='sent_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
