# Generated by Django 4.1.6 on 2023-08-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_page_sent_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='qc_status',
            field=models.CharField(choices=[('', ''), ('approved', 'Approved'), ('rejected', 'Rejected')], default='', help_text='This status is stands for Quality Check Status Defines whether a page is approved or rejected upon showing to a verifier after segmentation editing.', max_length=15),
        ),
    ]
