# Generated by Django 4.1.6 on 2023-09-27 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page', '0009_page_qc_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='qc_user',
            field=models.ForeignKey(blank=True, default=None, help_text='Indicates the user that performs the QC on this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_pages', to=settings.AUTH_USER_MODEL),
        ),
    ]
