# Generated by Django 4.1.6 on 2023-02-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='line',
            field=models.IntegerField(default=0),
        ),
    ]
