# Generated by Django 4.1.6 on 2023-02-21 11:12

from django.db import migrations, models
import word.models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0002_word_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='image',
            field=models.ImageField(blank=True, help_text='original word level cropped image', null=True, upload_to=word.models.get_image_path, verbose_name='Word Image'),
        ),
    ]
