# Generated by Django 4.1.6 on 2023-03-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0003_alter_word_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('cropped', 'Cropped'), ('sent_editing', 'Sent to Editing'), ('sent_verification', 'Sent to Verification')], default='new', max_length=50),
        ),
    ]
